filter:
    excluded_paths:
        - 'tests/*'
        - 'vdf2json/*'
tools:
    external_code_coverage:
        timeout: 200
        runs: 8

build:
  nodes:
    analysis:
      tests:
        override:
          - command: py-scrutinizer-run
            idle_timeout: 300

