#!/bin/sh
# Copyright © 2019 Collabora Ltd.
# SPDX-License-Identifier: MIT
# (see debian/copyright)

# Run tests from /usr/share/installed-tests/steam-runtime-tools-0
# via the gnome-desktop-testing-runner test harness (if available).

set -eu

exec gnome-desktop-testing-runner steam-runtime-tools-0
