#!/bin/sh

# run-in-scout — undo the Steam Runtime's environment and use
# scout, assuming the layout of the SteamLinuxRuntime depot.
#
# Copyright © 2019 Collabora Ltd.
#
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -eu

me="$(readlink -f "$0")"
here="${me%/*}"
me="${me##*/}"

if [ "x${STEAM_RUNTIME_CONTAINER_TEST-}" = x1 ]; then
    export PRESSURE_VESSEL_WRAP_GUI=1
fi

name=com.valvesoftware.SteamRuntime.Platform
arch=amd64,i386
suite=scout

if ! current_build_id="$(cat "${here}/${name}-${arch}-${suite}-buildid.txt")"; then
    # Ignore: there is no build ID in the depot.
    :
elif [ -d "${here}/${suite}_${current_build_id}/files" ] \
    && [ -d "${here}/${suite}" ] \
    && [ -L "${here}/${suite}" ] \
    && [ "x$(readlink "${here}/${suite}")" = "x${suite}_${current_build_id}" ]
then
    # Fast path: skip the locking and the deploy step if the correct runtime
    # is already in place.
    :
else
    # Take a lock on this directory while we deploy new runtimes, to avoid
    # two runs fighting.
    (
        unset LD_LIBRARY_PATH
        unset LD_PRELOAD
        "$here/pressure-vessel/bin/pressure-vessel-with-lock" \
            --create --write --wait \
            --lock-file "$here/.ref" \
            -- \
            "$here/deploy-runtime" \
            --suite=scout
    )
fi

export PRESSURE_VESSEL_RUNTIME_BASE="${here}"
export PRESSURE_VESSEL_RUNTIME="scout/files"
exec "$here/pressure-vessel/bin/pressure-vessel-unruntime" "$@"

# vim:set sw=4 sts=4 et:
