FROM @BASE_IMAGE@
COPY sources.list /etc/apt/sources.list.d/pressure-vessel.list

RUN \
set -eux; \
apt-get update; \
apt-get -y install \
    bubblewrap \
    libcapsule-tools-relocatable:amd64 \
    libcapsule-tools-relocatable:i386 \
    libblkid1 \
    libcap2 \
    libelf1:amd64 \
    libelf1:i386 \
    libffi6 \
    libglib2.0-0 \
    libmount1 \
    libpcre3 \
    libselinux1 \
    libsteam-runtime-tools-0-dev \
    libsteam-runtime-tools-0-helpers:amd64 \
    libsteam-runtime-tools-0-helpers:i386 \
    libxau6 \
    locales \
    pandoc \
    steam-runtime-tools-bin \
    zlib1g:amd64 \
    zlib1g:i386 \
    ${NULL+}
# Deliberately not including `rm -rf /var/lib/apt/lists/*`, because we
# need to be able to run `apt-get source` later

# vim:set sw=4 sts=4 et ft=dockerfile:
