#!/usr/bin/env groovy
/*
 * SPDX-License-Identifier: LGPL-2.1+
 *
 * Copyright © 2017-2018 Collabora Ltd
 *
 * This package is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This package is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this package.  If not, see
 * <http://www.gnu.org/licenses/>.
 */
@Library('steamos-ci') _

pipeline {
  options {
    timestamps()
    skipDefaultCheckout()
  }
  agent {
    label 'docker-slave'
  }
  environment {
    HOME="${env.WORKSPACE}"
    TMPDIR="${env.WORKSPACE}"
    PYTHONUNBUFFERED="1"
  }

  stages {
    stage ("pressure-vessel") {
      steps {
        sh '''
        git config --global user.name Jenkins
        git config --global user.email nobody@example.com
        '''
        checkoutCollaboraGitlab('steam/pressure-vessel', 'master', 'src')

        script {
          if (env.CI_DOCKER_REGISTRY_CRED == '') {
            dockerRegistryCred = null;
          }
          else {
            dockerRegistryCred = env.CI_DOCKER_REGISTRY_CRED;
          }

          docker.withRegistry("https://${env.CI_DOCKER_REGISTRY}", dockerRegistryCred) {
            docker.image("${env.CI_DOCKER_REGISTRY}/steamrt/sdk:scout").inside('--mount type=tmpfs,destination=/var/cache/apt/archives') {
              sh '''
              set -e
              if [ -d /usr/lib/libcapsule/relocatable ]; then
                make -C src
              else
                apt-get download libcapsule-tools-relocatable:amd64
                apt-get download libcapsule-tools-relocatable:i386
                dpkg-deb -x libcapsule-tools-relocatable_*_amd64.deb .
                dpkg-deb -x libcapsule-tools-relocatable_*_i386.deb .

                make -C src relocatabledir=$(pwd)/usr/lib/libcapsule/relocatable
              fi
              '''
            }
          }
        }

        archiveArtifacts 'src/pressure-vessel-*-bin.tar.gz'
        archiveArtifacts 'src/pressure-vessel-*-bin+src.tar.gz'
      }
    }
  }

  post {
    cleanup {
      deleteDir()
    }
  }
}
/* vim:set sw=2 sts=2 et: */
