#!/usr/bin/env groovy
/*
 * SPDX-License-Identifier: LGPL-2.1+
 *
 * Copyright © 2017-2018 Collabora Ltd
 *
 * This package is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This package is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this package.  If not, see
 * <http://www.gnu.org/licenses/>.
 */
@Library('steamos-ci') _

pipeline {
  agent {
    docker {
      label 'docker-slave'
      image "steamos/package-builder:${env.docker_label ?: 'brewmaster'}"
      registryUrl 'https://docker-registry.internal.collabora.com'
      registryCredentialsId 'ccu-docker-internal-collabora-com'
    }
  }
  environment {
    HOME="${env.WORKSPACE}"
    TMPDIR="${env.WORKSPACE}"
    PYTHONUNBUFFERED="1"
  }

  options {
    timestamps()
    skipDefaultCheckout()
  }

  stages {
    stage ("checkout") {
      steps {
        sh 'git config --global user.name Jenkins'
        sh 'git config --global user.email nobody@example.com'
        checkoutCollaboraGitlab('vivek/libcapsule', 'master', 'src')
        sh 'mkdir -p debs'
      }
    }

    stage("deb-build-snapshot") {
      steps {
        sh '( cd src && deb-build-snapshot -d ../debs -s -u localhost )'
      }
    }

    stage("Save output") {
      steps {
        archiveArtifacts artifacts: 'debs/**'
      }
    }
  }

  post {
    always {
      deleteDir()
    }
  }
}
